version: '3.2'
volumes: 
  postgres-data:
services:
  db:
    image: postgres
    volumes: 
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash
    volumes:
      - .:/project
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - db
      